# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d2fb1afd8dae56d166095293dca63d6b88f3ab289d61cd7c7749500c6cb7d169a65f7549c0e0d4ce018116109555e52e048bfc9171b423692dfd75e4dabb34c

test:
  secret_key_base: 37439085f052e59624771f67237de8768ace13d3993d7d82c8053a85d90bd9a95d3fd56597ed92dc09441dcdfb982d5c1ce385966fce3891431fab8c6b6598d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
